### ISSUE TITLE
Unable to re-send wavier.

### ISSUE THREAD

**Issue by yednapg** [codeday/www-clear#26]
Getting this error when sending wavier link to one specific person. Email Address DM'ed on discord for CodeDay Delhi.

```
Error: You tried to send to recipient(s) that have been marked as inactive. Found inactive addresses: EMAILADDRESS@gmail.com. Inactive recipients are ones that have generated a hard bounce, a spam complaint, or a manual suppression.: {"response":{"errors":[{"message":"You tried to send to recipient(s) that have been marked as inactive. Found inactive addresses: EMAILADDRESS@gmail.com. Inactive recipients are ones that have generated a hard bounce, a spam complaint, or a manual suppression.","path":["clear","sendWaiverReminder"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"statusCode":422,"code":406,"name":"InactiveRecipientsError","recipients":["EMAILADDRESS@gmail.com. Inactive recipients are ones that have generated a hard bounce","a spam complaint","or a manual suppression"],"stacktrace":["GraphQLError: You tried to send to recipient(s) that have been marked as inactive. Found inactive addresses: EMAILADDRESS@gmail.com. Inactive recipients are ones that have generated a hard bounce, a spam complaint, or a manual suppression.","    at Object.relocatedError (/app/node_modules/@graphql-tools/utils/index.cjs.js:3909:12)","    at mergeDataAndErrors (/app/node_modules/@graphql-tools/wrap/node_modules/@graphql-tools/delegate/index.cjs.js:1404:34)","    at /app/node_modules/@graphql-tools/wrap/node_modules/@graphql-tools/delegate/index.cjs.js:1432:66","    at Array.forEach (&lt;anonymous&gt;)","    at mergeDataAndErrors (/app/node_modules/@graphql-tools/wrap/node_modules/@graphql-tools/delegate/index.cjs.js:1430:27)","    at checkResultAndHandleErrors (/app/node_modules/@graphql-tools/wrap/node_modules/@graphql-tools/delegate/index.cjs.js:1393:38)","   at CheckResultAndHandleErrors.transformResult (/app/node_modules/@graphql-tools/wrap/node_modules/@graphql-tools/delegate/index.cjs.js:1389:16)","    at /app/node_modules/@graphql-tools/wrap/node_modules/@graphql-tools/delegate/index.cjs.js:1576:40","    at Array.reduceRight (&lt;anonymous&gt;)","    at Transformer.transformResult (/app/node_modules/@graphql-tools/wrap/node_modules/@graphql-tools/delegate/index.cjs.js:1575:37)","    at /app/node_modules/@graphql-tools/wrap/node_modules/@graphql-tools/delegate/index.cjs.js:1664:36","    at runMicrotasks (&lt;anonymous&gt;)","    at processTicksAndRejections (internal/process/task_queues.js:97:5)"]}}}],"data":{"clear":{"sendWaiverReminder":null}},"status":200,"headers":{"map":{"content-type":"application/json; charset=utf-8"}}},"request":{"query":"mutation sendWaiverReminder($where: ClearTicketWhereUniqueInput!) {\n  clear {\n    sendWaiverReminder(where: $where)\n  }\n}\n","variables":{"where":{"id":"clah2oxgj745193exku7xxxnk7l"}}}}
```

**Comment by tylermenezes** [comment]
This means the person's email is bad.
